name: reversevideoapi deploy
on: [push]
jobs:

  heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "reversevideoapi"
          heroku_email: "john_shenk@hotmail.com"
          usedocker: true
