name: reversevideoapi deploy
on: [push]
jobs:

  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
    - run: go get
    - run: go build -o reversevideoapi main.go
